name: Timer
on:
  # For pull request labels
  issues:
    types:
      ['labeled', 'unlabeled'].
  # For pull request labels
  pull_request:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: test_run
        uses: tbsmcd/label_timer@v2.2
        id: test_run
        with:
          # You can specify multiple labels separated by commas.
          targets: 'responding, requesting, needs_review'
          token: ${{ secrets.GITHUB_TOKEN }}
      # If you want to use the measurement results in later steps
      - name: checkout
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == 'responding' }}
        uses: actions/checkout@v2
      - name: add_time_label
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == 'responding' }}
        # outputs can be obtained as the following variables.
        #
        # If `github.event.action == labeled`.
        # ${ steps.test_run.outputs.url }} URL of the issue or pull request that was targeted.
        #
        # If `github.event.action == unlabeled`.
        # ${ steps.test_run.outputs.url }} URL of the issue or pull request that was targeted
        # ${ steps.test_run.outputs.passed_seconds }} Number of seconds between label assignment and removal
        # ${ steps.test_run.outputs.sum_seconds }} Number of seconds between labeling and deletion (total)
        run: |
          pip install requests
          python .github/example.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.url }} ${{ steps.test_run.outputs.sum_seconds }}